apiVersion: aam.globalsphare.com/v1alpha1
kind: WorkloadType
metadata:
  name: webservice
spec:
  parameter: |
    image:     string
    port:      *80 | int
    cmd?: [...string]
    args?: [...string]
    cpu?: string
    env?: [...{
      name:   string
      value?: string
      valueFrom?: {
        secretKeyRef: {
          name: string
          key:  string
        }
      }
    }]
    after?: string
  traits:
    - aam.globalsphare.com/v1alpha1/trait-ingress
