apiVersion: aam.globalsphare.com/v1alpha1
kind: WorkloadType
metadata:
  name: worker
spec:
  parameter: |
    image: string
    port:  *80 | int
    cmd?: [...string]
    args?: [...string]
    cpu?: string
    env?: [...{
        name:   string
        value?: string
        valueFrom?: {
            secretKeyRef: {
                name: string
                key:  string
            }
        }
    }]
    configs?: [...{
        path:     string
        subPath?: string
        data: [...{
            name:  string
            value: string
        }]
    }]
    storage?: {
        capacity: string
        path:     string
    }