apiVersion: aam.globalsphare.com/v1alpha1
kind: trait
metadata:
  name: dependency
spec:
  parameter: |
    authorization?: [...{
      service: string
      namespace: string
      resources?: [...{
        uri: string
        action: [...string]
      }]
    }]
    serviceentry?: [...{
      host: string
      port: int
      protocol: string
    }]
